apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
    - image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root1234"
      name: mysql8019
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306